name: riverpod_feature_generator
description: This is a code generation annotation for widget_gen package.
version: 0.0.2
homepage: https://furkanacar.dev
repository: https://github.com/AcarFurkan/riverpod_feature_generator

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  widget_gen_annotation: ^0.0.3
  build: ^2.0.0
  source_gen: ^1.2.0
  analyzer: '>=5.13.0 <7.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:



 