name: riverpod_feature_generator
description: This is a code generation annotation for widget_gen package.
version: 0.0.6
homepage: https://furkanacar.dev
repository: https://github.com/AcarFurkan/riverpod_feature_generator

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.0.0
  source_gen: ^1.3.2
  graphs: 2.2.0
  widget_gen_annotation: ^0.0.4
  analyzer: '>=5.12.0 <7.0.0'
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  build_verify: ^3.0.0


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:



 